### ISSUE TITLE
Move `twine-macros` integration tests to an `integration-tests` crate

### ISSUE THREAD

**Issue by dyreby** [isentropic-dev/twine#40]
The `compose_demo.rs` started in `twine-macro/tests` because it was just testing the `compose!` macro, but adding the `Component` trait in `twine-core` means we'll need to use `Component` in any integration tests.  This suggests that it's a true integration test and should live in the workspace root.

My understanding is that we can't have just a `tests` folder at the workspace level and have that work like it does in a crate.  Instead what you can do is have a new crate that contains all the integration tests.

I'm open to other names, but assuming we use `integration-tests` the workspace `Cargo.toml` will look like this:

```toml
[workspace]
members = [
    "twine-core",
    "twine-engine",
    "twine-macros",
    "integration-tests",
]

resolver = "2"

[workspace.dependencies]
twine-macros = { version = "0.1", path = "twine-macros" }
```

And we'll have an `integration-tests` directory with its own `Cargo.toml`:

```toml
[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
twine-core = { path = "../twine-core" }

[dev-dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.136"
serde_yaml = "0.9.34"
toml = "0.8.19"
```
